### ISSUE TITLE
Mod discussion

### ISSUE THREAD

**Issue by Solarstrike** [fewizz/NotEnoughIDs#12]
Feel free to discuss anything about the mod here.

**Comment by Solarstrike** [comment]
TehNut has called this mod a "hacky piece of shit".

**Comment by fewizz** [comment]
:smile:

**Comment by Solarstrike** [comment]
@fewizz You're happy over a negative comment??

**Comment by fewizz** [comment]
no, but TehNut is right.

**Comment by Solarstrike** [comment]
@fewizz Wait, so you're saying this isn't a mod, but a hack?

**Comment by Adaptivity** [comment]
@Solarstrike for god's sake please stop. Learn what means "hacky" in modding before saying something. NEID hacks into the game classes through ASM and doing changes because you can't do this differently. Nor game or Forge allows to do this. Any mod which is using ASM (There are a lot of them, they are usually called "Something"Core or "Something"Library) is a hack. You are using a lot of them and didn't notice this at all.
So, forget what TehNut said. If you are not a modder, you just can't understand this properly. Only Chosen can understand this.

**Comment by DPxKnightxZero** [comment]
@Adaptivity that was the best explanation about coding I have seen in a while. This must mean I am one of the chosen.

**Comment by Solarstrike** [comment]
@Adaptivity @DPxKnightxZero I understood that near-completely.

**Comment by Solarstrike** [comment]
Thank you @sfPlayer1
