### ISSUE TITLE
Not enough biomes IDs , I know its a common issue , heres an example

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [fewizz/NotEnoughIDs#79]
https://github.com/Glitchfiend/BiomesOPlenty/issues/1312

**Comment by ZombieHDGaming** [comment]
I provided an answer over here in #75 that is basically the same answer in that thread, but still.

**Comment by Pythonic-Rainbow** [comment]
@ZombieHDGaming while I already used JEID , That is NOT a solution for NEID itself.

**Comment by ZombieHDGaming** [comment]
@Pythonic-Rainbow Yes, you are correct, but NEID isn't being worked on anymore unless it's like a simple bug fix, hence why NEID only released one version (which was a simple ASM bug fix) since the last version and why people are switching to JEID instead. And from what I've gathered, fewizz full supports us and JEID.

Anyways, my point is, if you want this fixed in NEID, then you are going to be waiting months to maybe a year for fewizz or someone else to implement that into NEID, where as JEID already has this implemented and fewizz has not said anything against us advising people to take advantage of that fact. And that's assuming NEID will ever get a biome ID extension addition at all. We could fight this for hours, but realistically, this is probably the only solution that will happen for quite some time.

**Comment by Pythonic-Rainbow** [comment]
rip fewizz

**Comment by Pythonic-Rainbow** [comment]
So half year passed, for 1.12.2 this will be NEID + JEID. 1.13+ doesn't need extending IDs.
rip NEID
