### ISSUE TITLE
Strange Crash

### ISSUE THREAD

**Issue by TheAndreo16** [fewizz/NotEnoughIDs#99]
So, I'm playing 1.12.2 with a lot of mods and recently I added HBM Nuclear Tech and the world started crashing shortly after I enter it. I sent this crash report to them, and they recommended me posting it in here, since it envolves some problem with "new and old states of chunks". I hope someone here can help me with this. ´

[crash-2021-03-16_17.28.06-server.txt](https://github.com/fewizz/NotEnoughIDs/files/6152473/crash-2021-03-16_17.28.06-server.txt)

**Comment by fewizz** [comment]
Not related to NEID too. Mod's author sould add [here](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/blob/d7036aa6aebfb5b0a72b17e19fe8e832980c7da8/src/main/java/com/hbm/blocks/machine/MachineBattery.java#L73) something like `else return;`, so that it wont call world.setBlock if `state` isn't changed.

**Comment by TheAndreo16** [comment]
> Not related to NEID too. Mod's author should add [here](https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/blob/d7036aa6aebfb5b0a72b17e19fe8e832980c7da8/src/main/java/com/hbm/blocks/machine/MachineBattery.java#L73) something like `else return;`, so that it wont call world.setBlock if `state` isn't changed.

Any idea of which mod may have caused this crash?

**Comment by fewizz** [comment]
HBM Nuclear Tech port by @Drillgon200 , i guess

**Comment by fewizz** [comment]
Can you produce this only with `Nuclear Tech` and `NEID`?

**Comment by TheAndreo16** [comment]
I'll try. But I don't think so. 
Also, someone suggested that it's may also be a problem with Mekanis + Galacticraft. He said that, for some reason, the game runs out of IDs

**Comment by fewizz** [comment]
Any news on this?

**Comment by TheAndreo16** [comment]
I tried three cases:

1) With ONLY Hbm + NEID;
2)With Hbm + NEID + Mekanism + Galacticraft
3) With Hbm + NEID + Mekanism + Galacticraft + Logistic Pipes

All resulted in nothing. The game ran smooth. I also tried creating a new world, and surprisingly it didn't crash at all. I suspected Logistic Pipes could cause the crash, since it mostly occur when I open the Remote Controler, but now I don't have any idea of what mod can be causing it.

**Comment by TheAndreo16** [comment]
Just in case, I'm sending a print screen of my mods folder:
![mods](https://user-images.githubusercontent.com/72123938/112189754-13be2e80-8be3-11eb-8987-bf3892f27f39.png)

**Comment by fewizz** [comment]
Can i somehow get your modpack and world?

**Comment by TheAndreo16** [comment]
Yes, I'll try uplouding it and send you the link

**Comment by TheAndreo16** [comment]
Here, try and tell me if the link works:

https://drive.google.com/file/d/1zcfsdBd5e2b-TFZb2th7P5xcr_PvQDPn/view?usp=sharing

Also, feel free to roam the world, if you can.
Note: This world is not actually set in the overwolrd, but the  Lost Cities dimension

**Comment by TheAndreo16** [comment]
Just saw the link was removed. Add me ins Discord: TheAndreo#8440

**Comment by fewizz** [comment]
**Mystcraft** bug.
Happens, for example, with blocks that have `setBlockState` in `onBlockAdded`. (vanilla chest or HBM battery).
`World.setBlockState` needs old block state to compare with. It asks chunk at that position, and gets MystEmptyChunk, even though there were writes to that chunk through `setBlockState`. MystEmptyChunk **always** returns `AIR` as old blockstate. `Chunk.setBlockState` then writes changed block state to block storage and calls `onBlockAdded`, because new state (HBM's battery) and `AIR` are different. And then it repeats.

**Comment by fewizz** [comment]
[Mystcraft issue report](https://github.com/XCompWiz/Mystcraft-Issues/issues/394)
